# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_beauty

on:
  push:
  schedule:
  - cron: "1 7,12,19 * * *"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: npm install
    - run: node ./jd_beauty.js
